import { useSession } from "next-auth/react"
import Head from "next/head"
import Link from "next/link"
import { api } from "apple/utils/api"
import { RadioGroup, Radio, cn } from "@nextui-org/react"
import { DropdownItem as NextUIDropdownItem } from "@nextui-org/dropdown";
import { type DropdownItemProps } from "@nextui-org/react";

const DropdownItem = (props: DropdownItemProps) => {
    return <NextUIDropdownItem {...props} />;
};

interface RadioProps {
  children: React.ReactNode,
  value: string,
  description: string,
}

function CustomRadio ({ value, description }: RadioProps) {
  return (
    <Radio
      value={value}
      description={description}
      classNames={{
        wrapper: cn("border-red-500 hover:border-yellow-300"),
        control: cn("bg-red-500 hover:bg-blue-500"),
      }}
      className="m-3"
    >
      {value}
    </Radio>
  );
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Real people and Real estate</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="https://static.rdc.moveaws.com/favicon.ico" />
      </Head>
      <main className="flex min-h-full flex-col items-center justify-center bg-main-back">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <h1 className="text-5xl font-extrabold tracking-tight text-[#b3ffa1] sm:text-[5rem] drop-shadow-xl">
          Real people, Real estate
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-black/20 p-4 text-white hover:bg-black/10"
              href="/submit/deals"
            >
              <h3 className="text-2xl font-bold">Submit deals →</h3>
              <div className="text-lg">
                text text text text text text text text text text text text text text text text text text.
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-black/20 p-4 text-white hover:bg-black/10"
              href="/submit/buybox"
            >
              <h3 className="text-2xl font-bold">Submit buybox →</h3>
              <div className="text-lg">
                text text text text text text text text text text text text text text text text text text.
              </div>
            </Link>
          </div>
          <div className="flex flex-col items-center gap-2">
            <p className="text-2xl text-white">
              Hi, welcome to our website.
            </p>
            <AuthShowcase />
          </div>
        </div>
        <DropdownItem></DropdownItem>
        <div className="p-3 bg-white w-[200px] mb-2">
          <RadioGroup label="Plans" description="" color={ undefined } classNames={{
            wrapper: cn("border-red-500 hover:border-yellow-300 checked:border-white")
          }}>
            <CustomRadio description="" value="free">
              Free
            </CustomRadio>
            <CustomRadio description="" value="pro">
              Pro
            </CustomRadio>
            <CustomRadio
              description=""
              value="enterprise"
            >
              Enterprise
            </CustomRadio>
          </RadioGroup>
        </div>
        <div className="p-3 bg-white w-[200px]">
          <RadioGroup
            label="Select your favorite city"
            color="warning"
            defaultValue="london"
          >
            <Radio value="buenos-aires">Buenos Aires</Radio>
            <Radio value="sydney">Sydney</Radio>
            <Radio value="san-francisco">San Francisco</Radio>
            <Radio value="london">London</Radio>
            <Radio value="tokyo">Tokyo</Radio>
          </RadioGroup>
        </div>
      </main>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <Link
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        href={'https://discord.com/invite/reirev'} 
        target="_blank"
        >
        Join us
      </Link>
    </div>
  );
}
